version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  build-docker-image:
    docker:
      - image: docker:20.10.24
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
      - run:
          name: "Check Dockerfile existence"
          command: |
            if [ ! -f dockerfile ]; then
              echo "Dockerfile missing" && exit 1
            fi
            echo "Dockerfile found"
      - run:
          name: "Build Docker Image"
          command: "docker build -t myapp:latest ."
      - run:
          name: "Run and Test Container"
          command: |
            docker run --rm -d -p 8080:8080 --name test-container myapp:latest
            sleep 5
            curl -i http://localhost:8080 || (echo "Application not started" && exit 1)

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - build-docker-image
